name: 🏁 Windows Builds
on:
  workflow_call:
    inputs:
      base-branch:
        description: 'Base branch to use for the builds'
        type: string
      repo:
        description: 'Repository to use for the build'
        type: string
      tag:
        description: 'tag to use for the build'
        type: string
      module_flags:
        description: 'Extra module flags, e.g. module_webm_enabled=no'
        type: string
      template_module_flags:
        description: 'Extra module flags for template build, e.g. module_webm_enabled=no'
        type: string

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: ${{ inputs.base-branch }}
  SCONSFLAGS: verbose=yes warnings=extra strict_checks=yes debug_symbols=no ${{ inputs.module_flags }} use_static_cpp=yes
  # Keep this aligned with godot-nir-static's MinGW/LLVM UCRT builds:
  # https://github.com/godotengine/godot-nir-static/blob/master/.github/workflows/ci.yaml
  LLVM_MINGW_VERSION: 20251118
  LLVM_MINGW_PREFIX: ${{ github.workspace }}/llvm-mingw
  PYTHONIOENCODING: utf8

jobs:
  generate-mono-glue:
    runs-on: ubuntu-24.04
    name: Generate Mono glue
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.tag }}
          submodules: recursive

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwayland-bin mono-devel nuget

      - name: Force remove preinstalled .NET SDKs
        run: |
          sudo rm -rf /usr/share/dotnet/sdk/*

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.100'

      - name: Free disk space on runner
        run: |
          echo "Disk usage before:" && df -h
          sudo rm -rf /usr/local/lib/android
          echo "Disk usage after:" && df -h

      - name: Download pre-built AccessKit
        shell: sh
        id: accesskit-sdk
        run: |
          if python ./misc/scripts/install_accesskit.py; then
            echo "ACCESSKIT_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::AccessKit SDK installation failed, building without AccessKit support."
            echo "ACCESSKIT_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: windows-mono-glue-linux-editor-x86_64
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Mono tools build (pre-glue)
        run: |
          if [ -n "${{ github.event.number }}" ]; then
            export BUILD_NAME="gh-${{ github.event.number }}"
          else
            export BUILD_NAME="gh"
          fi
          scons platform=linuxbsd target=editor verbose=yes warnings=extra strict_checks=yes debug_symbols=no arch=x86_64 lto=none ${{ inputs.module_flags }} module_mono_enabled=yes mono_glue=no accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }} "cache_path=${{ github.workspace }}/.scons_cache/" redirect_build_objects=no
          ls -l bin

      - name: Generate C# glue
        run: |
          ./bin/godot.linuxbsd.editor.x86_64.mono --headless --generate-mono-glue ./modules/mono/glue

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: windows-mono-glue-linux-editor-x86_64
          purge-cache-script: misc/scripts/purge_cache.py
        continue-on-error: true

      - name: Upload Mono glue
        uses: actions/upload-artifact@v7
        with:
          name: windows-mono-glue
          path: modules/mono/glue

  build-windows:
    needs: generate-mono-glue
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor, arch=x86_64)
            target: editor
            scons-flags: arch=x86_64
            compiler-flags: use_mingw=yes
            lto: lto=full
            toolchain: mingw-gcc
            build-mono: false
            mono-flags: ''

          - name: Editor (target=editor, arch=arm64)
            target: editor
            scons-flags: arch=arm64
            compiler-flags: use_mingw=yes use_llvm=yes
            lto: lto=thin
            toolchain: mingw-llvm
            build-mono: false
            mono-flags: ''

          - name: Template (target=template_release, arch=x86_64)
            target: template_release
            scons-flags: arch=x86_64
            compiler-flags: use_mingw=yes
            lto: lto=full
            toolchain: mingw-gcc
            build-mono: false
            mono-flags: ''

          - name: Template (target=template_release, arch=x86_32)
            target: template_release
            scons-flags: arch=x86_32
            compiler-flags: use_mingw=yes
            lto: lto=full
            toolchain: mingw-gcc
            build-mono: false
            mono-flags: ''

          - name: Template (target=template_release, arch=arm64)
            target: template_release
            scons-flags: arch=arm64
            compiler-flags: use_mingw=yes use_llvm=yes
            lto: lto=thin
            toolchain: mingw-llvm
            build-mono: false
            mono-flags: ''

          - name: Template (target=template_debug, arch=x86_64)
            target: template_debug
            scons-flags: arch=x86_64
            compiler-flags: use_mingw=yes
            lto: lto=full
            toolchain: mingw-gcc
            build-mono: false
            mono-flags: ''

          - name: Template (target=template_debug, arch=x86_32)
            target: template_debug
            scons-flags: arch=x86_32
            compiler-flags: use_mingw=yes
            lto: lto=full
            toolchain: mingw-gcc
            build-mono: false
            mono-flags: ''

          - name: Template (target=template_debug, arch=arm64)
            target: template_debug
            scons-flags: arch=arm64
            compiler-flags: use_mingw=yes use_llvm=yes
            lto: lto=thin
            toolchain: mingw-llvm
            build-mono: false
            mono-flags: ''

          - name: Editor Mono (target=editor, arch=x86_64)
            target: editor
            scons-flags: arch=x86_64
            compiler-flags: use_mingw=yes
            lto: lto=full
            toolchain: mingw-gcc
            build-mono: true
            mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

          - name: Template Mono (target=template_release, arch=x86_64)
            target: template_release
            scons-flags: arch=x86_64
            compiler-flags: use_mingw=yes
            lto: lto=full
            toolchain: mingw-gcc
            build-mono: true
            mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

          - name: Template Mono (target=template_debug, arch=x86_64)
            target: template_debug
            scons-flags: arch=x86_64
            compiler-flags: use_mingw=yes
            lto: lto=full
            toolchain: mingw-gcc
            build-mono: true
            mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

          - name: Editor Mono (target=editor, arch=arm64)
            target: editor
            scons-flags: arch=arm64
            compiler-flags: use_mingw=yes use_llvm=yes
            lto: lto=thin
            toolchain: mingw-llvm
            build-mono: true
            mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

          - name: Template Mono (target=template_release, arch=arm64)
            target: template_release
            scons-flags: arch=arm64
            compiler-flags: use_mingw=yes use_llvm=yes
            lto: lto=thin
            toolchain: mingw-llvm
            build-mono: true
            mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

          - name: Template Mono (target=template_debug, arch=arm64)
            target: template_debug
            scons-flags: arch=arm64
            compiler-flags: use_mingw=yes use_llvm=yes
            lto: lto=thin
            toolchain: mingw-llvm
            build-mono: true
            mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.tag }}
          submodules: recursive

      - name: Setup MinGW-w64 GCC
        if: matrix.toolchain == 'mingw-gcc'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            binutils-mingw-w64 \
            gcc-mingw-w64-i686-posix \
            g++-mingw-w64-i686-posix \
            gcc-mingw-w64-x86-64-posix \
            g++-mingw-w64-x86-64-posix \
            mingw-w64-tools
          sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
          sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          i686-w64-mingw32-g++ --version
          x86_64-w64-mingw32-g++ --version

      - name: Setup llvm-mingw
        if: matrix.toolchain == 'mingw-llvm'
        run: |
          curl -L -o llvm-mingw.tar.xz https://github.com/mstorsjo/llvm-mingw/releases/download/${LLVM_MINGW_VERSION}/llvm-mingw-${LLVM_MINGW_VERSION}-ucrt-ubuntu-22.04-x86_64.tar.xz
          tar -xf llvm-mingw.tar.xz
          rm llvm-mingw.tar.xz
          mv llvm-mingw-* "$LLVM_MINGW_PREFIX"
          echo "MINGW_PREFIX=$LLVM_MINGW_PREFIX" >> "$GITHUB_ENV"
          echo "$LLVM_MINGW_PREFIX/bin" >> "$GITHUB_PATH"

      - name: Setup D3D12 MinGW helper tools
        run: |
          sudo apt-get update
          sudo apt-get install -y binutils-mingw-w64 mingw-w64-tools

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: windows-${{ matrix.target }}${{ matrix.mono-flags }}-${{ matrix.scons-flags }}-${{ matrix.toolchain }}-${{ matrix.lto }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

# Mono
      - name: Install Mono toolchain
        if: matrix.build-mono
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-devel nuget

      - name: Force remove preinstalled .NET SDKs
        if: matrix.build-mono
        run: |
          sudo rm -rf /usr/share/dotnet/sdk/*

      - name: Setup .NET SDK
        if: matrix.build-mono
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.100'

      - name: Download Mono glue
        if: matrix.build-mono
        uses: actions/download-artifact@v8
        with:
          name: windows-mono-glue
          path: modules/mono/glue

      - name: Download Direct3D 12 SDK components
        shell: sh
        id: d3d12-sdk
        run: |
          D3D12_ARGS=
          if [ -n "${MINGW_PREFIX:-}" ]; then
            D3D12_ARGS="--mingw_prefix=${MINGW_PREFIX}"
          fi
          if python ./misc/scripts/install_d3d12_sdk_windows.py ${D3D12_ARGS}; then
            echo "D3D12_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::Windows: Direct3D 12 SDK installation failed, building without Direct3D 12 support."
            echo "D3D12_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi
        continue-on-error: true

      - name: Download pre-built ANGLE
        shell: sh
        id: angle-sdk
        run: |
          if python ./misc/scripts/install_angle.py; then
            echo "ANGLE_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::ANGLE SDK installation failed, building without ANGLE support."
            echo "ANGLE_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi

      - name: Download WinRT components
        shell: sh
        run: python ./misc/scripts/install_winrt.py
        continue-on-error: true

      - name: Download pre-built AccessKit
        shell: sh
        id: accesskit-sdk
        run: |
          if python ./misc/scripts/install_accesskit.py; then
            echo "ACCESSKIT_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::AccessKit SDK installation failed, building without AccessKit support."
            echo "ACCESSKIT_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi

# Compilation

      - name: Compilation (editor)
        if: matrix.target == 'editor'
        run: |
          if [ -n "${{ github.event.number }}" ]; then
            export BUILD_NAME="gh-${{ github.event.number }}"
          else
            export BUILD_NAME="gh"
          fi
          scons platform=windows target=${{ matrix.target }} ${{ env.SCONSFLAGS }} ${{ matrix.scons-flags }} ${{ matrix.compiler-flags }} ${{ matrix.lto }} ${{ inputs.module_flags }} ${{ matrix.mono-flags }} d3d12=${{ steps.d3d12-sdk.outputs.D3D12_ENABLED }} angle=${{ steps.angle-sdk.outputs.ANGLE_ENABLED }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }} "cache_path=${{ github.workspace }}/.scons_cache/" redirect_build_objects=no
          ls -l bin

      - name: Compilation (template)
        if: matrix.target != 'editor'
        run: |
          rm -rf editor
          if [ -n "${{ github.event.number }}" ]; then
            export BUILD_NAME="gh-${{ github.event.number }}"
          else
            export BUILD_NAME="gh"
          fi
          scons platform=windows target=${{ matrix.target }} ${{ env.SCONSFLAGS }} ${{ matrix.scons-flags }} ${{ matrix.compiler-flags }} ${{ matrix.lto }} ${{ inputs.template_module_flags }} ${{ matrix.mono-flags }} d3d12=${{ steps.d3d12-sdk.outputs.D3D12_ENABLED }} angle=${{ steps.angle-sdk.outputs.ANGLE_ENABLED }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }} "cache_path=${{ github.workspace }}/.scons_cache/" redirect_build_objects=no
          ls -l bin

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: windows-${{ matrix.target }}${{ matrix.mono-flags }}-${{ matrix.scons-flags }}-${{ matrix.toolchain }}-${{ matrix.lto }}
          purge-cache-script: misc/scripts/purge_cache.py
        continue-on-error: true

      - name: Build .NET solutions
        if: matrix.build-mono
        run: |
          dotnet --info
          ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=windows --werror

      - name: Prepare artifact
        run: |
          rm -rf bin/build_deps

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-${{ matrix.target }}${{ matrix.mono-flags }}-${{ matrix.scons-flags }}-${{ matrix.toolchain }}-${{ matrix.lto }}
          path: bin
